version: "3"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123l
    ports:
      - 3306:3306
    volumes:
      - /Users/ayajirob/sql/mysql:/docker-entrypoint-initdb.d
